### PR TITLE
Bug fixes needs testing

### PR DESCRIPTION
**Pull request by Aaronsss**
implementing feedback from #4

### CODE REVIEW

**Comment by martinglass** [comment]
Thanks for these updates, Aaron. They all seem to work and the Pi5 fan is operating too.
I've got a fork at 
https://github.com/martinglass/RH-Setup
In that fork, I've corrected the text of Readme.md - mainly spelling/grammar.
I'm too much of a novice with Github to do it properly, so can you copy/paste the Readme.md from my fork into Aaronsss/main, if you want to use the text corrections ?

**Comment by Aaronsss** [comment]
Cheers @martinglass I have copied in the typo fixes and put it through word to check it too :)

**Comment by Aaronsss** [comment]
presumably when you say the fan works it is turning on and off? and isnt just always on?

**Comment by martinglass** [comment]
Oh! I can't confirm as I only checked the fan was on. If you want to me test that out properly, I'll have to do it another time/day

**Comment by Aaronsss** [comment]
If you could check when you get the chance that would be great. The expected behaviour is at 48C they should turn on and then turn off at 38C

**Pull request merged**
